package com.demo.flink.constant;

import java.util.List;

public class Constants {

    public static List<String> REGULAR_LOCATIONS = List.of("18 MARINA GARDENS DRIVE GARDENS BY THE BAY (VISITOR CENTRE) SINGAPORE 018953",
            "1 BAYFRONT AVENUE MARINA BAY SANDS SINGAPORE 018971",
            "80 AIRPORT BOULEVARD CHANGI AIRPORT TERMINAL 1 BUILDING SINGAPORE 819642",
            "585 NORTH BRIDGE ROAD RAFFLES HOSPITAL SINGAPORE 188770",
            "3 LOWER KENT RIDGE ROAD NATIONAL UNIVERSITY HOSPITAL SINGAPORE 119073",
            "21 SELETAR AEROSPACE ROAD 1 SELETAR AIRPORT PASSENGER TERMINAL SINGAPORE 797405",
            "1 EXPO DRIVE SINGAPORE EXPO SINGAPORE 486150",
            "3 TEMASEK BOULEVARD SUNTEC CITY MALL SINGAPORE 038983",
            "81 TELOK BLANGAH ROAD HARBOURFRONT SINGAPORE SINGAPORE 098867",
            "3C RIVER VALLEY ROAD CLARKE QUAY SINGAPORE 179022",
            "1 MARITIME SQUARE HARBOURFRONT CENTRE SINGAPORE 099253",
            "23 SERANGOON CENTRAL NEX SINGAPORE 556083",
            "1 HARBOURFRONT WALK VIVOCITY SINGAPORE 098585",
            "23 CHURCH STREET CAPITAL SQUARE SINGAPORE 049481",
            "80 PASIR PANJANG ROAD MAPLETREE BUSINESS CITY SINGAPORE 117372",
            "5 CHANGI BUSINESS PARK CENTRAL 1 CHANGI CITY SINGAPORE 486038",
            "78 AIRPORT BOULEVARD JEWEL CHANGI AIRPORT SINGAPORE 819666",
            "13 COMPUTING DRIVE NATIONAL UNIVERSITY OF SINGAPORE (COMPUTING1) SINGAPORE 117417",
            "11 WOODLANDS CROSSING WOODLANDS TRAIN CHECKPOINT SINGAPORE 738103",
            "50 STAMFORD ROAD SINGAPORE MANAGEMENT UNIVERSITY (LEE KONG CHIAN SCH OF BUSINESS) SINGAPORE 178899",
            "10 PASIR PANJANG ROAD MAPLETREE BUSINESS CITY SINGAPORE 117438",
            "20 PASIR PANJANG ROAD MAPLETREE BUSINESS CITY SINGAPORE 117439",
            "15 CHANGI BUSINESS PARK CENTRAL 1 SINGAPORE 486057",
            "1 SHENTON WAY ONE SHENTON SINGAPORE 068803",
            "1 RAFFLES PLACE ONE RAFFLES PLACE SINGAPORE 048616"
            );

    public static List<String> LONG_WEEKEND_LOCATIONS = List.of("80 AIRPORT BOULEVARD CHANGI AIRPORT TERMINAL 1 BUILDING SINGAPORE 819642",
            "60 AIRPORT BOULEVARD CHANGI AIRPORT TERMINAL 2 BUILDING SINGAPORE 819643",
            "65 AIRPORT BOULEVARD CHANGI AIRPORT TERMINAL 3 BUILDING SINGAPORE 819663",
            "10 AIRPORT BOULEVARD CHANGI AIRPORT TERMINAL 4 SINGAPORE 819665",
            "11 WOODLANDS CROSSING WOODLANDS TRAIN CHECKPOINT SINGAPORE 738103",
            "21 WOODLANDS CROSSING BLK A (WOODLANDS CHECKPOINT) SINGAPORE 738203",
            "21 WOODLANDS CROSSING BLK B (WOODLANDS CHECKPOINT) SINGAPORE 738203",
            "21 WOODLANDS CROSSING BLK C (WOODLANDS CHECKPOINT) SINGAPORE 738203",
            "21 WOODLANDS CROSSING BLK D (WOODLANDS CHECKPOINT) SINGAPORE 738203",
            "21 WOODLANDS CROSSING BLK E (WOODLANDS CHECKPOINT) SINGAPORE 738203",
            "50 TANAH MERAH FERRY ROAD TANAH MERAH FERRY TERMINAL SINGAPORE 498833",
            "81 TELOK BLANGAH ROAD HARBOURFRONT SINGAPORE SINGAPORE 098867");


    public static List<String> NORMAL_WEEKEND_LOCATIONS = List.of("18 MARINA GARDENS DRIVE GARDENS BY THE BAY (VISITOR CENTRE) SINGAPORE 018953",
            "80 MANDAI LAKE ROAD SINGAPORE ZOO SINGAPORE 729826",
            "50 CLUNY PARK ROAD THE GARAGE (SINGAPORE BOTANIC GARDENS) SINGAPORE 257488",
            "1 BAYFRONT AVENUE MARINA BAY SANDS SINGAPORE 018971",
            "8 SENTOSA GATEWAY S.E.A. AQUARIUM SINGAPORE 098269",
            "920 EAST COAST PARKWAY PARKLAND GREEN SINGAPORE 449875",
            "30 SENTOSA GATEWAY UNIVERSAL STUDIOS SINGAPORE SINGAPORE 098140",
            "30 RAFFLES AVENUE SINGAPORE FLYER SINGAPORE 039803",
            "2 ANDOVER ROAD CHANGI BEACH CLUB SINGAPORE 509984",
            "80 MANDAI LAKE ROAD NIGHT SAFARI SINGAPORE 729826",
            "80 MANDAI LAKE ROAD RIVER SAFARI SINGAPORE 729826",
            "21 ESPLANADE DRIVE MERLION PARK (ONE FULLERTON) SINGAPORE 038980",
            "3 NEW BUGIS STREET NEW BUGIS STREET SINGAPORE 188867",
            "31 MARINA COASTAL DRIVE MARINA SOUTH PIER SINGAPORE 018988"





            );


    public static List<String> FRIDAY_EVENING_LOCATIONS = List.of("23 ARAB STREET KAMPONG GLAM CONSERVATION AREA SINGAPORE 199722",
            "3C RIVER VALLEY ROAD CLARKE QUAY SINGAPORE 179022",
            "145 SYED ALWI ROAD MUSTAFA CENTRE SINGAPORE 207704",
            "46 PAGODA STREET CHINATOWN HERITAGE CENTRE SINGAPORE 059205",
            "1 BAYFRONT AVENUE MARINA BAY SANDS SINGAPORE 018971",
            "321 ORCHARD ROAD ORCHARD SHOPPING CENTRE SINGAPORE 238866"
            );


}
